# Generated by Django 5.0.3 on 2024-03-17 05:46

import blog_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0003_alter_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='id',
            field=models.CharField(default=blog_api.models.getUUID, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
