# Generated by Django 5.0.3 on 2024-03-17 05:46

import auth_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=auth_api.models.getUUID, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
